GET http://localhost:3000/users

###

GET http://localhost:3000/users/1666


###

POST http://localhost:3000/users
Content-Type: application/json
# {
#     "message": "hello world!"
# }

{
    "username": "SteadyBready",
    "password": "thatsarelayracewithabouquettheysayKyougonmarrymines",
    "fav_player": "StephenCurry"
}